name: 🔄 IPTV Playlist Otomatik Güncelleme

on:
  schedule:
    # Her gün saat 06:00'da çalış (UTC+3 için 03:00 UTC)
    - cron: '0 3 * * *'
    # Her 12 saatte bir de çalış
    - cron: '0 15 * * *'
  workflow_dispatch: # Manuel çalıştırma için
    inputs:
      force_update:
        description: 'Zorla güncelleme yap'
        required: false
        default: 'false'

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Repository'yi indir
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: 🐍 Python'u kur
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 📦 Bağımlılıkları yükle
      run: |
        pip install requests
        
    - name: 🔍 Playlist'i kontrol et
      run: |
        echo "🚀 IPTV Playlist kontrolü başlıyor..."
        python check_links.py
        
    - name: 📊 Değişiklikleri kontrol et
      id: changes
      run: |
        if git diff --quiet playlist.m3u; then
          echo "changed=false" >> $GITHUB_OUTPUT
          echo "✅ Hiçbir değişiklik yok, tüm linkler çalışıyor!"
        else
          echo "changed=true" >> $GITHUB_OUTPUT
          echo "🔄 Playlist'te değişiklikler tespit edildi!"
        fi
        
    - name: 📝 Commit ve Push
      if: steps.changes.outputs.changed == 'true' || github.event.inputs.force_update == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "🤖 IPTV Bot"
        
        # Değişiklikleri göster
        echo "📋 Yapılan değişiklikler:"
        git diff --stat playlist.m3u || echo "Yeni dosya oluşturuldu"
        
        # Commit ve push
        git add playlist.m3u
        
        # Commit mesajı için tarih
        TARIH=$(date '+%d.%m.%Y %H:%M')
        
        if git diff --staged --quiet; then
          echo "ℹ️ Commit edilecek değişiklik yok"
        else
          git commit -m "🔄 Otomatik playlist güncellemesi - $TARIH

          🤖 GitHub Actions tarafından otomatik olarak güncellendi
          📅 Tarih: $TARIH
          🔗 Bozuk linkler temizlendi"
          
          git push
          echo "✅ Değişiklikler başarıyla push edildi!"
        fi
        
    - name: 📈 Özet rapor
      run: |
        echo "## 📊 Güncelleme Raporu" >> $GITHUB_STEP_SUMMARY
        echo "📅 **Tarih:** $(date '+%d.%m.%Y %H:%M:%S')" >> $GITHUB_STEP_SUMMARY
        echo "🔗 **Repository:** ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ steps.changes.outputs.changed }}" == "true" ]; then
          echo "✅ **Durum:** Playlist güncellendi" >> $GITHUB_STEP_SUMMARY
          echo "🔄 **Değişiklik:** Bozuk linkler temizlendi" >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ **Durum:** Tüm linkler çalışıyor" >> $GITHUB_STEP_SUMMARY
          echo "🎉 **Sonuç:** Güncelleme gerekmedi" >> $GITHUB_STEP_SUMMARY
        fi
