name: "Auto Update IPTV"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'
    - cron: '0 18 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install requests
    - name: Update playlist
      run: python check_links.py
    - name: Commit
      run: |
        git config user.email "bot@github.com"
        git config user.name "IPTV Bot"
        git add playlist.m3u
        git diff --staged --quiet || (git commit -m "🔄 Updated $(date)" && git push)
